# Generated by Django 4.0.4 on 2022-05-27 14:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaloffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 15, 43, 13, 875266)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='allergy',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='healthInsurance',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='vaccination',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
