# Generated by Django 4.0.4 on 2022-05-27 15:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaloffice', '0006_alter_appointment_date_alter_user_begindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 13, 48, 700909)),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
