# Generated by Django 4.0.4 on 2022-05-27 15:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicaloffice', '0007_alter_appointment_date_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 16, 31, 28, 903085)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicaloffice.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicaloffice.user'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='allergy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='healthInsurance',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicaloffice.patient'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='vaccination',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicaloffice.user'),
        ),
    ]
